name: Export and Upload to App Store Connect

on:
  workflow_dispatch:
    inputs:
      ChooseProvisionType:
        description: "证书类型(ad-hoc/app-store/development)"
        required: true
        default: "app-store"

# 使用并发
concurrency:
  # 组名
  group: ${{ github.workflow }}-${{ github.ref }}
  # 是否取消当前正在进行的进程
  cancel-in-progress: true

jobs:
  Archive:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: bundle install
      run: |
        bundle install

  UploadMetadata:
    needs: Archive
    uses: NickeyTestOrganization/TestProject114/.github/workflows/UploadMetadata.yml@main
    with:
      upload_screenshots: false


  InstallPods:
    needs: UploadMetadata
    runs-on: self-hosted
    steps:
    - name: Copy Podlock File
      run: |
        BACKUP_DIR=$(basename "$PWD")
        BACKUP_DIR_PATH=${HOME}"/Documents/Backup/"
        if [ -f ${BACKUP_DIR_PATH}${BACKUP_DIR}/"Podfile.lock" ]; then
            echo "Podfile.lock exist!"
            cp -f ${BACKUP_DIR_PATH}${BACKUP_DIR}/Podfile.lock ./Podfile.lock
        fi
    - name: Pod Install
      run: |
        # 重新拉取pod
        pod install --repo-update

  ArchiveAndExport:
    needs: InstallPods
    uses: NickeyTestOrganization/TestProject114/.github/workflows/ArchiveAndUpload.yml@main
    with:
      ChooseProvisionType: "app-store"
