name: Export and Upload to App Store Connect

on:
  workflow_dispatch:
    inputs:
      ChooseProvisionType:
        description: "证书类型(ad-hoc/app-store/development)"
        required: true
        default: "app-store"

# 使用并发
concurrency:
  # 组名
  group: ${{ github.workflow }}-${{ github.ref }}
  # 是否取消当前正在进行的进程
  cancel-in-progress: true

jobs:
  Archive:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: bundle install
        run: |
          bundle install

  UploadMetadata:
    uses: NickeyTestOrganization/TestProject114/.github/workflows/UploadMetadata.yml@main
    with:
      upload_screenshots: false

  # upload:
  #   needs: Archive
  #   runs-on: self-hosted
  #   steps:
  #     - name: Check ipa file
  #       run: |
  #         BACKUP_DIR=$(basename "$PWD")
  #         BACKUP_DIR_PATH=${HOME}"/Documents/Backup/"
  #         FASTLANE_RELEASE_DIR="./fastlane/Release/"
  #         IPA_NAME="OOG114.ipa"

  #         if [ ! -f "${FASTLANE_RELEASE_DIR}/${IPA_NAME}" ]; then
  #             echo "未找到ipa文件，从Backup文件夹中复制"
  #             if [ ! -d "${FASTLANE_RELEASE_DIR}" ]; then
  #                 echo "未找到Release文件夹，创建文件夹"
  #                 mkdir "${FASTLANE_RELEASE_DIR}"
  #             fi
  #             cp -r "${BACKUP_DIR_PATH}${BACKUP_DIR}/${IPA_NAME}" "${FASTLANE_RELEASE_DIR}"
  #             echo "复制完成"
  #         fi
  #         echo "开始上传ipa文件"

  #     - name: Upload binary
  #       run: |
  #         bundle exec fastlane upload_binary
