name: Upload Metadata to App Store Connect

on:
  workflow_call:
    inputs:
      upload_screenshots:
        required: true
        type: boolean
      isNewVersion:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      upload_screenshots:
        description: "是否上传screenshots"
        required: true
        type: boolean
        default: false
      isNewVersion:
        description: "是否是在新版本上传"
        required: false
        type: string
        default: "false"

# 使用并发
# concurrency:
#   # 组名
#   group: ${{ github.workflow }}-${{ github.ref }}-metadata
#   # 是否取消当前正在进行的进程
#   cancel-in-progress: true

jobs:
  Prepare:
    if: github.event.workflow == '.github/workflows/UploadMetadata.yml'
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: bundle install
      run: |
        bundle install
  UploadMetadata:
    # if: ${{ needs.Prepare.result  == 'success' || needs.Prepare.result == 'skipped' }}
    if: ${{ always() }}
    needs: Prepare
    runs-on: self-hosted
    steps:
    # - name: Slack upload metadata begin message
    #   run: |
    #     bundle exec fastlane slack_message messageText:"开始上传Metadata\n*OOG111 - Home Workout*\n<!subteam^S02KJ2JPCLE> <!subteam^S01K6B7A338> 开始上传metadata\n*推送程序员：* ${{ github.actor }}\n*时间：* $(TZ=$TZ-8 date +%Y年%m月%d日%H:%M:%S)\n"
    - name: Dump job context
      run: echo '${{ toJSON(job) }}'

    - name: Dump steps context
      run: echo '${{ toJSON(steps) }}'

    - name: Upload metadata
      run: |
        bundle exec fastlane upload_metadata kId:'${{ secrets.KEY_ID }}' issueId:'${{ secrets.ISSUE_ID }}' p8PrivateKey:'${{ secrets.P8_PRIVATE_KEY }}' upload_Screenshots:${{ inputs.upload_screenshots }} isNewVersion:${{ inputs.isNewVersion }}

    # - name: Slack upload metadata finish message
    #   run: |
    #     bundle exec fastlane slack_message messageText:"上传Metadata完成\n*OOG111 - Home Workout*\n<!subteam^S02KJ2JPCLE> <!subteam^S01K6B7A338> 上传metadata完成\n*推送程序员：* ${{ github.actor }}\n*时间：* $(TZ=$TZ-8 date +%Y年%m月%d日%H:%M:%S)\n"
